//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroYz.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int IdTeacher { get; set; }
        public int IdStudent { get; set; }
        public int IdStatus { get; set; }
        public System.DateTime DateEvent { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Student Student { get; set; }
        public virtual User User { get; set; }
    }
}
