//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroYz.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int id { get; set; }
        public int idStudent { get; set; }
        public int IdDisciplen { get; set; }
        public int Evaluation { get; set; }
        public int IdNameGroup { get; set; }
    
        public virtual Disciplen Disciplen { get; set; }
        public virtual NameGroup NameGroup { get; set; }
        public virtual Student Student { get; set; }
    }
}
