//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroYz.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int id { get; set; }
        public int idStudent { get; set; }
        public int IdDisciplen { get; set; }
        public int Evaluation { get; set; }
        public int IdNameGroup { get; set; }
    
        public virtual Disciplen Disciplen { get; set; }
        public virtual NameGroup NameGroup { get; set; }
        public virtual Student Student { get; set; }
    }
}
