//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroYz.DataFilesApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeroEntities : DbContext
    {
        public ZeroEntities()
            : base("name=ZeroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disciplen> Disciplen { get; set; }
        public virtual DbSet<FormTime> FormTime { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<NameGroup> NameGroup { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Special> Special { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<YearAdd> YearAdd { get; set; }
    }
}
